sudo: false

language: node_js
node_js:
- '6'
- '8'

env:
  global:
  - GH_REF: wreact/wreact

script:
  - npm run build
  - npm run lint
  - npm test

after_success:
  - openssl aes-256-cbc -K $encrypted_885a9f732cff_key -iv $encrypted_885a9f732cff_iv -in .travis_rsa.enc -out ./.travis_rsa -d
  - mv ./.travis_rsa $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa
  - ./bin/deploy-demo.sh
